title: Mao ShengZi's Homepage
page-top-title: Mao ShengZi
top-section-bg-text: Computer Science
home-subtitle: Mao ShengZi&ensp;|&ensp;猫剩子
copyright-text: '&copy; Mao ShengZi 2023-2025. All Rights Reserved.'
